//creamos una baraja
var baraja =[{ palo: 'corazones',
               numero: 'AS',
               valor: 1,
               font: 'N',
                },
             { palo: 'corazones',
               numero: 'DOS',
               valor: 2,
               font: 'O',
                },
             { palo: 'corazones',
               numero: 'TRES',
               valor: 3,
               font: 'P',
                },
             { palo: 'corazones',
               numero: 'CUATRO',
               valor: 4,
               font: 'Q',
                },
             { palo: 'corazones',
               numero: 'CINCO',
               valor: 5,
               font: 'R',
                },
             { palo: 'corazones',
               numero: 'SEIS',
               valor: 6,
               font: 'S',
                },
             {palo: 'corazones',
               numero: 'SIETE',
               valor: 7,
               font: 'T',
                },
             { palo: 'corazones',
               numero: 'OCHO',
               valor: 8,
               font: 'U',
                },
             { palo: 'corazones',
               numero: 'NUEVE',
               valor: 9,
               font: 'V',
                },
             { palo: 'corazones',
               numero: 'DIEZ',
               valor: 10,
               font: 'W',
                },
             { palo: 'corazones',
               numero: 'JOTA',
               valor: 11,
               font: 'X',
                },
             { palo: 'corazones',
               numero: 'DAMA',
               valor: 12,
               font: 'Y',
                },
               { palo: 'corazones',
                numero: 'REY',
                valor: 13,
                font: 'Z',
                }, 
             { palo: 'picas',
               numero: 'AS',
               valor: 1,
               font: 'a',
                },
             { palo: 'picas',
               numero: 'DOS',
               valor: 2,
               font: 'b',
                },
             { palo: 'picas',
               numero: 'TRES',
               valor: 3,
               font: 'c',
                },
             { palo: 'picas',
               numero: 'CUATRO',
               valor: 4,
               font: 'd',
                },
             { palo: 'picas',
               numero: 'CINCO',
               valor: 5,
               font: 'e',             
                },
             { palo: 'picas',
               numero: 'SEIS',
               valor: 6,
               font: 'f',
                },
             {palo: 'picas',
               numero: 'SIETE',
               valor: 7,
               font: 'g',
                },
             { palo: 'picas',
               numero: 'OCHO',
               valor: 8,
               font: 'h',
                },
             { palo: 'picas',
               numero: 'NUEVE',
               valor: 9,
               font: 'i',
                },
             { palo: 'picas',
               numero: 'DIEZ',
               valor: 10,
               font: 'j',
                },
             { palo: 'picas',
               numero: 'JOTA',
               valor: 11,
               font: 'k',
                },
             { palo: 'picas',
               numero: 'DAMA',
               valor: 12,
               font: 'l',
                },
               { palo: 'picas',
                numero: 'REY',
                valor: 13,
                font: 'm',
                },
             { palo: 'treboles',
               numero: 'AS',
               valor: 1,
               font: 'n',
                },
             { palo: 'treboles',
               numero: 'DOS',
               valor: 2,
               font: 'o',
                },
             { palo: 'treboles',
               numero: 'TRES',
               valor: 3,
               font: 'p',
                },
             { palo: 'treboles',
               numero: 'CUATRO',
               valor: 4,
               font: 'q',
                },
             { palo: 'treboles',
               numero: 'CINCO',
               valor: 5,
               font: 'r',
                },
             { palo: 'treboles',
               numero: 'SEIS',
               valor: 6,
               font: 's',
                },
             {palo: 'treboles',
               numero: 'SIETE',
               valor: 7,
               font: 't',
                },
             { palo: 'treboles',
               numero: 'OCHO',
               valor: 8,
               font: 'u',
                },
             { palo: 'treboles',
               numero: 'NUEVE',
               valor: 9,
               font: 'v',
                },
             { palo: 'treboles',
               numero: 'DIEZ',
               valor: 10,
              font: 'w',
                },
             { palo: 'treboles',
               numero: 'JOTA',
               valor: 11,
               font: 'x',
                },
             { palo: 'treboles',
               numero: 'DAMA',
               valor: 12,
               font: 'y',
                },
               { palo: 'treboles',
                numero: 'REY',
                valor: 13,
                font: 'z',
                },
             { palo: 'diamantes',
               numero: 'AS',
               valor: 1,
               font: 'A',
                },
             { palo: 'diamantes',
               numero: 'DOS',
               valor: 2,
               font: 'B',
                },
             { palo: 'diamantes',
               numero: 'TRES',
               valor: 3,
               font: 'C',
                },
             { palo: 'diamantes',
               numero: 'CUATRO',
               valor: 4,
               font: 'D',
                },
             { palo: 'diamantes',
               numero: 'CINCO',
               valor: 5,
               font: 'E',
                },
             { palo: 'diamantes',
               numero: 'SEIS',
               valor: 6,
               font: 'F',
                },
             {palo: 'diamantes',
               numero: 'SIETE',
               valor: 7,
               font: 'G',
                },
             { palo: 'diamantes',
               numero: 'OCHO',
               valor: 8,
               font: 'H',
                },
             { palo: 'diamantes',
               numero: 'NUEVE',
               valor: 9,
               font: 'I',
                },
             { palo: 'diamantes',
               numero: 'DIEZ',
               valor: 10,
               font: 'J',
                },
             { palo: 'diamantes',
               numero: 'JOTA',
               valor: 11,
               font: 'K',
                },
             { palo: 'diamantes',
               numero: 'DAMA',
               valor: 12,
               font: 'L',
                },
               { palo: 'diamantes',
                numero: 'REY',
                valor: 13,
                font: 'M',
                },
];