//Creamos una baraja
var baraja = [{palo: "corazones",
              numero: "as",
              valor: 1,
              },
              {palo: "corazones",
              numero: "DOS",
              valor: 2,
              },{palo: "corazones",
              numero: "TRES",
              valor: 3,
              },
              {palo: "corazones",
              numero: "CUATRO",
              valor: 4,
              },
              {palo: "corazones",
              numero: "CINCO",
              valor: 5,
              },
              {palo: "corazones",
              numero: "SEIS",
              valor: 6,
              },
              {palo: "corazones",
              numero: "SIETE",
              valor: 7,
              },
              {palo: "corazones",
              numero: "OCHO",
              valor: 8,
              },
              {palo: "corazones",
              numero: "NUEVE",
              valor: 9,
              },
              {palo: "corazones",
              numero: "DIEZ",
              valor: 10,
              },
              {palo: "corazones",
              numero: "J",
              valor: 11,
              },
              {palo: "corazones",
              numero: "Q",
              valor: 12,
              },
              {palo: "corazones",
              numero: "K",
              valor: 13,
              }, 
              
            //Palo 2  
              
              {palo: "picas",
              numero: "as",
              valor: 1,
              },
              {palo: "picas",
              numero: "DOS",
              valor: 2,
              },{palo: "picas",
              numero: "TRES",
              valor: 3,
              },
              {palo: "picas",
              numero: "CUATRO",
              valor: 4,
              },
              {palo: "picas",
              numero: "CINCO",
              valor: 5,
              },
              {palo: "picas",
              numero: "SEIS",
              valor: 6,
              },
              {palo: "picas",
              numero: "SIETE",
              valor: 7,
              },
              {palo: "picas",
              numero: "OCHO",
              valor: 8,
              },
              {palo: "picas",
              numero: "NUEVE",
              valor: 9,
              },
              {palo: "picas",
              numero: "DIEZ",
              valor: 10,
              },
              {palo: "picas",
              numero: "J",
              valor: 11,
              },
              {palo: "picas",
              numero: "Q",
              valor: 12,
              },
              {palo: "picas",
              numero: "K",
              valor: 13,
              }, 
              
              //Palo 3
              
              {palo: "trebol",
              numero: "as",
              valor: 1,
              },
              {palo: "trebol",
              numero: "DOS",
              valor: 2,
              },{palo: "trebol",
              numero: "TRES",
              valor: 3,
              },
              {palo: "trebol",
              numero: "CUATRO",
              valor: 4,
              },
              {palo: "trebol",
              numero: "CINCO",
              valor: 5,
              },
              {palo: "trebol",
              numero: "SEIS",
              valor: 6,
              },
              {palo: "trebol",
              numero: "SIETE",
              valor: 7,
              },
              {palo: "trebol",
              numero: "OCHO",
              valor: 8,
              },
              {palo: "trebol",
              numero: "NUEVE",
              valor: 9,
              },
              {palo: "trebol",
              numero: "DIEZ",
              valor: 10,
              },
              {palo: "trebol",
              numero: "J",
              valor: 11,
              },
              {palo: "trebol",
              numero: "Q",
              valor: 12,
              },
              {palo: "trebol",
              numero: "K",
              valor: 13,
              }, 
              
              //Palo 4
              
              {palo: "diamante",
              numero: "as",
              valor: 1,
              },
              {palo: "diamante",
              numero: "DOS",
              valor: 2,
              },{palo: "diamante",
              numero: "TRES",
              valor: 3,
              },
              {palo: "diamante",
              numero: "CUATRO",
              valor: 4,
              },
              {palo: "diamante",
              numero: "CINCO",
              valor: 5,
              },
              {palo: "diamante",
              numero: "SEIS",
              valor: 6,
              },
              {palo: "diamante",
              numero: "SIETE",
              valor: 7,
              },
              {palo: "diamante",
              numero: "OCHO",
              valor: 8,
              },
              {palo: "diamante",
              numero: "NUEVE",
              valor: 9,
              },
              {palo: "diamante",
              numero: "DIEZ",
              valor: 10,
              },
              {palo: "diamante",
              numero: "J",
              valor: 11,
              },
              {palo: "diamante",
              numero: "Q",
              valor: 12,
              },
              {palo: "diamante",
              numero: "K",
              valor: 13,
              } 
];
